/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.ControleFinanceiro;
import model.Despesa;
import model.Importador;
import model.Lancamento;
import model.Receita;
import model.TipoDespesa;
import model.TipoReceita;

/**
 *
 * @author helenas
 */
public class AppUi extends javax.swing.JFrame {
        ControleFinanceiro cf = new ControleFinanceiro("Helena");
        
       
       
        
        
    /**
     * Creates new form AppUi
     */
    public AppUi() throws IOException {
            
        
        initComponents();
        Importador importador = new Importador(cf);
        importador.carregarArquivo(new File("C:\\Users\\helenas\\Downloads\\teste.csv"));
        lbTitular.setText(cf.getTitular());
        lbSaldo.setText(String.valueOf("R$: " + cf.getSaldo()));
       
    }
    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTitular = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSaldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btIncluirReceita = new javax.swing.JButton();
        btIncluirDespesa = new javax.swing.JButton();
        btListarReceitas = new javax.swing.JButton();
        btListarDespesas = new javax.swing.JButton();
        btListarLancamentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        jLabel1.setText("Titular:");

        lbTitular.setText("jLabel2");

        jLabel2.setText("Saldo Atual:");

        lbSaldo.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSaldo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitular)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbSaldo))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos"));

        btIncluirReceita.setBackground(new java.awt.Color(204, 255, 204));
        btIncluirReceita.setForeground(new java.awt.Color(102, 102, 102));
        btIncluirReceita.setText("Incluir receita");
        btIncluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirReceitaActionPerformed(evt);
            }
        });

        btIncluirDespesa.setBackground(new java.awt.Color(204, 255, 204));
        btIncluirDespesa.setForeground(new java.awt.Color(102, 102, 102));
        btIncluirDespesa.setText("Incluir despesa");
        btIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirDespesaActionPerformed(evt);
            }
        });

        btListarReceitas.setBackground(new java.awt.Color(204, 204, 255));
        btListarReceitas.setForeground(new java.awt.Color(102, 102, 102));
        btListarReceitas.setText("Listar receitas");
        btListarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarReceitasActionPerformed(evt);
            }
        });

        btListarDespesas.setBackground(new java.awt.Color(204, 204, 255));
        btListarDespesas.setForeground(new java.awt.Color(102, 102, 102));
        btListarDespesas.setText("Listar despesa");
        btListarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarDespesasActionPerformed(evt);
            }
        });

        btListarLancamentos.setBackground(new java.awt.Color(255, 204, 204));
        btListarLancamentos.setForeground(new java.awt.Color(102, 102, 102));
        btListarLancamentos.setText("Listar todos os lançamentos");
        btListarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarLancamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIncluirReceita)
                    .addComponent(btListarReceitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btIncluirDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btListarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btListarLancamentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluirReceita)
                    .addComponent(btIncluirDespesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListarDespesas)
                    .addComponent(btListarReceitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btListarLancamentos)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirReceitaActionPerformed
       IncluirReceitaUi incluirReceita = new IncluirReceitaUi(this, true);
       incluirReceita.setVisible(true);
       
       Receita receita = new Receita(0.0, LocalDate.of(2000, 8, 4), TipoReceita.DECIMO_TERCEIRO);
       receita = incluirReceita.getReceita();
       
            try {
                cf.inlcuirReceita(receita);
            } catch (IOException ex) {
                Logger.getLogger(AppUi.class.getName()).log(Level.SEVERE, null, ex);
            }
       
      
              
    }//GEN-LAST:event_btIncluirReceitaActionPerformed

    private void btListarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarLancamentosActionPerformed
        ListarLancamentosUi listarLancamentos = new ListarLancamentosUi(this, true);
        listarLancamentos.listarLancamentos(cf);
        listarLancamentos.setVisible(true);
        
        
    }//GEN-LAST:event_btListarLancamentosActionPerformed

    private void btIncluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirDespesaActionPerformed
      IncluirDespesaUi incluirDespesa = new IncluirDespesaUi(this, true);
      incluirDespesa.setVisible(true);
      
       Despesa despesa = new Despesa(0.0, LocalDate.of(2000, 8, 4), TipoDespesa.SAUDE);
       despesa = incluirDespesa.getDespesa();
        try {
                cf.incluirDespesa(despesa);
            } catch (IOException ex) {
                Logger.getLogger(AppUi.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btIncluirDespesaActionPerformed

    private void btListarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarReceitasActionPerformed
       ListarReceitasUi listarReceitas = new ListarReceitasUi(this, true);
       listarReceitas.listarReceitas(cf);
       listarReceitas.setVisible(true);
    }//GEN-LAST:event_btListarReceitasActionPerformed

    private void btListarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarDespesasActionPerformed
        ListarDespesasUi listarDespesas = new ListarDespesasUi(this, true);
         listarDespesas.listarDespesas(cf);
        listarDespesas.setVisible(true);
    
       
    }//GEN-LAST:event_btListarDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AppUi().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AppUi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluirDespesa;
    private javax.swing.JButton btIncluirReceita;
    private javax.swing.JButton btListarDespesas;
    private javax.swing.JButton btListarLancamentos;
    private javax.swing.JButton btListarReceitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JLabel lbTitular;
    // End of variables declaration//GEN-END:variables
}
